[general]
# Configuration directory, replaces variable CONFIG_DIR
config-dir = "/Users/ksmiley/.config/webkitten"
# Content filter used in web views
content-filter = "CONFIG_DIR/filter.json"
# Allow browser plugins to load, such as Flash and Silverlight
allow-plugins = false
# Font for the command bar
bar-font = { size = 13, family = "Monaco" }
# Currently disabled until this works per site
# Open in private mode by default
# private-browsing = true

[new-frame]
# Don't open a new window for cmd clicks
opens-in-focused-window = true

[window]
# First page opened with a new window
start-page = "file://CONFIG_DIR/start_page.html"

[commands.keybindings]
back = "cmd ["
forward = "cmd ]"
reload = "cmd r"

newwindow = "cmd n"
buffernext = "cmd }"
bufferprev = "cmd {"
buffernew = "cmd t"
close = "cmd w"

focus-bar = "ctrl space"
append = "cmd l"

find = "cmd f"
endfind = "shift cmd f"

[commands]
search-paths = ["CONFIG_DIR/commands"]
default = "go-or-search"

# Commands invoked after a document is created but before subresources are loaded
on-load-uri = ["user-content"]

# Currently disabled since this doesn't work for sites that don't support https
# Commands invoked when a URI is requested but before it is loaded
# on-request-uri = ["enforce-https"]

[user-content]
# Search paths for user scripts and stylesheets evaluated after the document is
# loaded but before subresources finish loading. Content is loaded on a
# per-site basis using page hostname as a key. Example: `example.com.js` and
# `example.com.css` will be loaded on `http://example.com/stuff`.
site-paths = ["/Users/ksmiley/.css", "/Users/ksmiley/.js"]
# default-paths = ["CONFIG_DIR/"]

# Currently disabled until this works per site
# [sites."github.com"]
# private-browsing = false
# [sites."pinboard.in"]
# private-browsing = false
